### ISSUE TITLE
v-gallery vuepress

### ISSUE THREAD

**Issue by shriaviator** [TerryZ/v-gallery#8]
using v-gallery in vue press 

v-gallery works satis during dev 
Below error during build

`ReferenceError: document is not defined
    at n (node_modules/v-gallery/dist/v-gallery.js:1:2026)
    at o (node_modules/v-gallery/dist/v-gallery.js:1:1856)
    at t.exports (node_modules/v-gallery/dist/v-gallery.js:1:3540)
    at Object.<anonymous> (node_modules/v-gallery/dist/v-gallery.js:1:14711)
    at e (node_modules/v-gallery/dist/v-gallery.js:1:348)
    at Object.<anonymous> (node_modules/v-gallery/dist/v-gallery.js:1:3903)
    at e (node_modules/v-gallery/dist/v-gallery.js:1:348)
    at Object.<anonymous> (node_modules/v-gallery/dist/v-gallery.js:1:11594)
    at e (node_modules/v-gallery/dist/v-gallery.js:1:348)
    at Object.<anonymous> (node_modules/v-gallery/dist/v-gallery.js:1:11471)
    at e (node_modules/v-gallery/dist/v-gallery.js:1:348)
    at server-bundle.js:6537:566`

- any suggestions ? , it works on the v-gallery documentation site using vuepres 
## Request 
 if you could point to the original docs for the v-gallery documentation site on git hub that would be highly helpful

**Comment by TerryZ** [comment]
You can try dynamically import

https://vuepress.vuejs.org/guide/using-vue.html

https://github.com/vuejs/vuepress/issues/442

**Comment by shriaviator** [comment]
- Can u point to  the repository for the v-gallery documentation { orginal repo} to c how it is implemented & learn  , I want to also  use the other plugins created by U via the same method in vuepress
-

**Comment by TerryZ** [comment]
`.vuepress/enhanceApp.js` file for example

```js

import Gallery from 'v-gallery'

export default ({
  Vue,
  options,
  router,
  siteData
}) => {
  if (typeof process === 'undefined') {
    Vue.use(Gallery)
  }
}
```

or

```js
export default ({
  Vue,
  options,
  router,
  siteData
}) => {
  import('v-gallery').then(resp => {
    Vue.use(resp.default)
  })
}
```


More references: https://vuepress-examples.netlify.app/demos/plugins/

**Comment by shriaviator** [comment]
- Gr8 , Clarifies everything , Appreciate the  prompt response . Thanks  :)
